apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdspostgresql25
spec:
  providerConfigRef:
    name: "account-dev-aws-provider-ap-south"
  forProvider:
    region: ap-south-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "12.13"
    skipFinalSnapshotBeforeDeletion: true
    tags:
      - key: "Name"
        value: "crossplane-rdspostgresql"
      - key: "Owner"
        value: "kushal.halder@finbox.in"
      - key: "Pipeline"
        value: "crossplane"
      - key: "ResourceType"
        value: "rds"
      - key: "Stage"
        value: "dev"
      - key : "Team"
        value: "infra"
      - key: crossplane-kind	
        value: rdsinstance.database.aws.crossplane.io	
      - key: crossplane-name	
        value: rdspostgresql25	
      - key: crossplane-providerconfig	
        value: account-dev-aws-provider-ap-south
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: aws-rdspostgresql-conn
