apiVersion: opensearchservice.aws.crossplane.io/v1alpha1
kind: Domain
metadata:
  name: domain-eks-dev-cluster
spec:
  providerConfigRef:
    name: "account-dev-aws-provider-ap-south"
  forProvider:
    # accessPolicies:
    clusterConfig:
      coldStorageOptions:
        enabled: false
      dedicatedMasterCount: 1
      dedicatedMasterEnabled: true
      dedicatedMasterType: t3.medium.search
      instanceCount: 1
      instanceType: t3.medium.search
      warmCount: 0
      warmEnabled: false
      # warmType: 
      zoneAwarenessEnabled: false
      # zoneAwarenessConfig: 
    congnitoOptions: 
      enabled: false
    domainEndpointOptions:
      enforceHTTPS: true
    ebsOptions:
      ebsEnabled: false
    encryptionAtRestOptions:
      enabled: false
    engineVersion: OpenSearch_1.0
    name: domain-eks-dev-cluster
    region: ap-south-1
    vpcOptions:
      securityGroupIdRefs:
        - name: sg-0942dd7253b8f6efb
      subnetIdRefs:  
        - name: subnet-0380d630149acdb23
        - name: subnet-00520b8925cddfb59
        - name: subnet-0e7fcd765f4cec5b2  
    tags:
      - key: "Name"
        value: "crossplane-domain-eks-dev-cluster"
      - key : "Team"
        value: "infra"
      - key: "Owner"
        value: "kushal.halder@finbox.in"
      - key: "ResourceType"
        value: "opensearch"
      - key: "Pipeline"
        value: "crossplane"
      - key: "Stage"
        value: "dev"