apiVersion: cache.aws.crossplane.io/v1alpha1
kind: CacheCluster
metadata:
  name: kyc-redis-prod-cluster
spec:
  providerConfigRef:
    name: "default"
  forProvider:
    region: ap-south-1
    applyImmediately: true
    cacheNodeType: cache.r6g.large
    cacheSubnetGroupName: redis-subnetgroup-kyc-prod-cluster
    engine: redis
    engineVersion: "7.0"
    numCacheNodes: 1
    securityGroupIds:
      - sg-0a01bf518d99b2abc
    tags:
      - key: "Name"
        value: "kyc-redis"
      - key : "Team"
        value: "kyc"
      - key: "Owner"
        value: "kushal.halder@finbox.in"
      - key: "ResourceType"
        value: "elasticcache"
      - key: "Pipeline"
        value: "kyc"
      - key: "Stage"
        value: "prod"