---
apiVersion: kafka.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: kafka-elt
spec:
  forProvider:
    clusterName: kafka-elt
    region: ap-south-1
    brokerNodeGroupInfo:
      clientSubnets:
        - subnet-0380d630149acdb23
        - subnet-00520b8925cddfb59
        - subnet-0e7fcd765f4cec5b2
      securityGroups:
        - sg-0942dd7253b8f6efb
      instanceType: kafka.t3.small
      storageInfo:
        ebsStorageInfo:
          volumeSize: 1
    kafkaVersion: 2.6.1
    configurationInfo:
      arnRef:
        name: kafka-elt-configuration
      revision: 1
    numberOfBrokerNodes: 3
    tags:
      Name: crossplane-domain-eks-dev-cluster
      Team: infra
      Owner: kushal.halder@finbox.in
      ResourceType: kafka
      Pipeline: crossplane
      Stage: dev
  providerConfigRef:
    name: "account-dev-aws-provider-ap-south"