apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: kyc-files
spec:
  providerConfigRef:
    name: "default"
  forProvider:
    acl: private
    locationConstraint: ap-south-1
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
  writeConnectionSecretToRef:
    name: kyc-s3
    namespace: crossplane-system