apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: ef-kyc-files
spec:
  providerConfigRef:
    name: "default"
  deletionPolicy: Orphan
  forProvider:
    locationConstraint: ap-south-1
    objectOwnership: BucketOwnerPreferred
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
  writeConnectionSecretToRef:
    name: kyc-s3
    namespace: crossplane-system