apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-2
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  syncPolicy:
    automated:
      selfHeal: true
  components:
    - name: wf-poc-app-2
      type: webservice
      properties:
        image: oamdev/helloworld-python:v1
        env:
          - name: "TARGET"
            value: "ArgoCD"
        port: 8080
